export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_PAYMENT_REQUEST = "ORDER_PAYMENT_REQUEST";
export const ORDER_PAYMENT_SUCCESS = "ORDER_PAYMENT_SUCCESS";
export const ORDER_PAYMENT_FAIL = "ORDER_PAYMENT_FAIL";
export const ORDER_PAYMENT_RESET = "ORDER_PAYMENT_RESET";

export const MYORDERS_REQUEST = "MYORDERS_REQUEST";
export const MYORDERS_SUCCESS = "MYORDERS_SUCCESS";
export const MYORDERS_FAIL = "MYORDERS_FAIL";

export const ORDERS_ALL_LIST_REQUEST = "ORDERS_ALL_LIST_REQUEST";
export const ORDERS_ALL_LIST_SUCCESS = "ORDERS_ALL_LIST_SUCCESS";
export const ORDERS_ALL_LIST_FAIL = "ORDERS_ALL_LIST_FAIL";

export const ORDER_DELIVERED_REQUEST = "ORDER_DELIVERED_REQUEST";
export const ORDER_DELIVERED_SUCCESS = "ORDER_DELIVERED_SUCCESS";
export const ORDER_DELIVERED_FAIL = "ORDER_DELIVERED_FAIL";
