export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODCUT_LIST_FAIL = "PRODCUT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODCUT_DETAILS_FAIL = "PRODCUT_DETAILS_FAIL";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODCUT_DELETE_FAIL = "PRODCUT_DELETE_FAIL";
export const PRODCUT_DELETE_RESET = "PRODCUT_DELETE_RESET";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODCUT_CREATE_FAIL = "PRODCUT_CREATE_FAIL";
export const PRODCUT_CREATE_RESET = "PRODCUT_CREATE_RESET";

export const PRODUCT_EDIT_REQUEST = "PRODUCT_EDIT_REQUEST";
export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS";
export const PRODCUT_EDIT_FAIL = "PRODCUT_EDIT_FAIL";
export const PRODCUT_EDIT_RESET = "PRODCUT_EDIT_RESET";

export const PRODUCT_REVIEW_REQUEST = "PRODUCT_REVIEW_REQUEST";
export const PRODUCT_REVIEW_SUCCESS = "PRODUCT_REVIEW_SUCCESS";
export const PRODCUT_REVIEW_FAIL = "PRODCUT_REVIEW_FAIL";
export const PRODCUT_REVIEW_RESET = "PRODCUT_REVIEW_RESET";

export const PRODUCT_TOP_REQUEST = "PRODUCT_TOP_REQUEST";
export const PRODUCT_TOP_SUCCESS = "PRODUCT_TOP_SUCCESS";
export const PRODCUT_TOP_FAIL = "PRODCUT_TOP_FAIL";
