export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const REG_TO_LOGIN = "REG_TO_LOGIN";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const DETAILS_USER_REQUEST = "DETAILS_USER_REQUEST";
export const DETAILS_USER_SUCCESS = "DETAILS_USER_SUCCESS";
export const DETAILS_USER_FAIL = "DETAILS_USER_FAIL";

export const DETAILS_UPDATE_REQUESTED = "DETAILS_UPDATE_REQUESTED";
export const DETAILS_UPDATE_SUCCESS = "DETAILS_UPDATE_SUCCESS";
export const DETAILS_UPDATE_FAIL = "DETAILS_UPDATE_FAIL";

export const LIST_USER_REQUEST = "LIST_USER_REQUEST";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const LIST_USER_FAIL = "LIST_USER_FAIL";
export const LIST_USER_RESET = "LIST_USER_RESET";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const UPDATE_ADMIN_USER_REQUEST = "UPDATE_ADMIN_USER_REQUEST";
export const UPDATE_ADMIN_USER_SUCCESS = "UPDATE_ADMIN_USER_SUCCESS";
export const UPDATE_ADMIN_USER_FAIL = "UPDATE_ADMIN_USER_FAIL";
